theme: jekyll-theme-midnight
include:- Home: index.md
include:- Local Installation: localInstallation.md
include:- Coding Style: codingStyle.md
include:- Functionality Validation: functionalityValidation.md
        
