theme: jekyll-theme-cayman
pages:
  - Home: index
  - Using git: github
  - Local Installation: localInstallation.md
  - Coding Style: codingStyle
  - Functionality Validation: functionalityValidation
  - BrAPI Implementation: brapiImplementation.md
  - Webapp: webapp.md
  - Web Service: webService.md
  - 4P : 4p.md
twitter:
  username: PHISphenomics
